### ISSUE TITLE
Bind does not work

### ISSUE THREAD

**Issue by fokaaas** [makatymba2001/Rozklad.KPI#1]
It's not possible to bind any group in the Telegram bot

![image](https://github.com/makatymba2001/Rozklad.KPI/assets/114052215/89f32f2a-5a41-44bb-841d-1d687b6d08c4)

**Actual result:** no response
**Expected result:** group has bound to current chat

**Platforms:** Telegram Mobile, Telegram Desktop

**Comment by SleepyG11** [comment]
Fixed.
